use DB_RESTAURANT;

CREATE TABLE PRODUCTO(
	IDPRODUCTO INT NOT NULL PRIMARY KEY IDENTITY, 
	DESCRIPCION VARCHAR(100) NOT NULL, 
	PRECIO_UNI DECIMAL(10,2) NOT NULL,
	PRECIO_AD DECIMAL(10,2) NOT NULL,
	CREATEBY VARCHAR(100) NOT NULL,
	CREATEDATE DATETIME NOT NULL
);

CREATE TABLE MENU(
	IDMENU INT NOT NULL PRIMARY KEY IDENTITY, 
	NOMBRE_MENU VARCHAR(50) NOT NULL, 
	PRECIO DECIMAL(10,2) NOT NULL, 
	CREATEBY VARCHAR(50) NOT NULL,
	CREATEDATE DATETIME NOT NULL
);

CREATE TABLE MENU_DETALLE(
	IDMENUDETALLE INT NOT NULL PRIMARY KEY IDENTITY, 
	IDMENU INT NOT NULL, 
	IDPRODUCTO INT NOT NULL, 
	CREATEBY VARCHAR(50) NOT NULL, 
	CREATEDATE DATETIME NOT NULL
	FOREIGN KEY(IDMENU) REFERENCES MENU(IDMENU),
	FOREIGN KEY(IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY IDENTITY, 
	NOMBRE VARCHAR(50) NOT NULL, 
	APELLIDO VARCHAR(50) NOT NULL, 
	NIT VARCHAR(15) NOT NULL, 
	DPI VARCHAR(12) NOT NULL,
	CREATEBY VARCHAR(50) NOT NULL, 
	CREATEDATE DATETIME NOT NULL
);

CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL PRIMARY KEY IDENTITY, 
	NOMBRE VARCHAR(50) NOT NULL, 
	APELLIDO VARCHAR(50) NOT NULL,
	DPI VARCHAR(12) NOT NULL,
	ESTADO INT NOT NULL DEFAULT 0,
	CREATEBY VARCHAR(50) NOT NULL,
	CREATEDATE DATETIME NOT NULL
);

CREATE TABLE FACTURA(
	IDFACTURA INT NOT NULL PRIMARY KEY IDENTITY, 
	IDCLIENTE INT NOT NULL,
	IDUSUARIO INT NOT NULL,
	FECHA DATETIME NOT NULL,
	TOTAL DECIMAL(10,2) NOT NULL,
	CREATEBY VARCHAR(50) NOT NULL,
	CREATEDATE DATETIME NOT NULL
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

CREATE TABLE ORDEN(
	IDORDEN INT NOT NULL PRIMARY KEY IDENTITY, 
	IDORDENNUM VARCHAR(12) NOT NULL,
	IDMENU INT NOT NULL, 
	CREATEBY VARCHAR(50) NOT NULL,
	CREATEDATE DATETIME NOT NULL,
	FOREIGN KEY (IDMENU) REFERENCES MENU(IDMENU)
);

CREATE TABLE DETALLE_FACTURA(
	IDDETALLEFACTURA INT NOT NULL PRIMARY KEY IDENTITY,
	IDFACTURA INT NOT NULL, 
	IDORDEN INT NOT NULL,
	CREATEBY VARCHAR(50) NOT NULL,
	CREATEDATE DATETIME NOT NULL
	FOREIGN KEY (IDFACTURA) REFERENCES FACTURA(IDFACTURA),
	FOREIGN KEY (IDORDEN) REFERENCES ORDEN(IDORDEN)
);

CREATE TABLE ORDEN_DETALLE(
	IDORDENDETALLE INT NOT NULL PRIMARY KEY IDENTITY,
	IDORDEN INT NOT NULL,
	IDPRODUCTO INT NOT NULL,
	CREATEBY VARCHAR(50) NOT NULL,
	CREATEDATE DATETIME NOT NULL,
	FOREIGN KEY (IDORDEN) REFERENCES ORDEN(IDORDEN),
	FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
);